FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod ./
# COPY go.sum ./ (if exists)
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/bin/api ./cmd/api

FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/bin/api /app/api

EXPOSE 8080

CMD ["/app/api"]
