package postgres

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/lib/pq"

	"github.com/ISIS4426-2026/Plataforma-MOOC/internal/domain"
)

// pgErrUniqueViolation is the SQLSTATE code Postgres reports when a UNIQUE
// constraint is violated, such as registering an already used email.
const pgErrUniqueViolation = "23505"

// UserRepository is the PostgreSQL implementation of domain.UserRepository.
type UserRepository struct {
	db *sql.DB
}

// Compile-time proof that the concrete type still satisfies the domain port.
var _ domain.UserRepository = (*UserRepository)(nil)

func NewUserRepository(db *sql.DB) *UserRepository {
	return &UserRepository{db: db}
}

const userColumns = `id, email, password_hash, full_name, role, status, created_at, updated_at`

// Create inserts a user and fills in the values generated by the database.
//
// The id, created_at and updated_at columns carry defaults in the schema, so
// they are returned rather than assigned by the caller: that keeps a single
// source of truth for identifiers and timestamps.
func (r *UserRepository) Create(ctx context.Context, user *domain.User) error {
	const query = `
		INSERT INTO users (email, password_hash, full_name, role, status)
		VALUES ($1, $2, $3, $4, $5)
		RETURNING id, created_at, updated_at`

	err := r.db.QueryRowContext(ctx, query,
		user.Email,
		user.PasswordHash,
		user.FullName,
		user.Role,
		user.Status,
	).Scan(&user.ID, &user.CreatedAt, &user.UpdatedAt)

	if err != nil {
		var pqErr *pq.Error
		if errors.As(err, &pqErr) && pqErr.Code == pgErrUniqueViolation {
			return fmt.Errorf("create user with email %q: %w", user.Email, domain.ErrConflict)
		}
		return fmt.Errorf("create user: %w", err)
	}

	return nil
}

func (r *UserRepository) GetByID(ctx context.Context, id string) (*domain.User, error) {
	query := `SELECT ` + userColumns + ` FROM users WHERE id = $1`
	return r.queryOne(ctx, query, id)
}

// GetByEmail looks the user up by exact email match, mirroring the UNIQUE
// constraint on the column. Callers are responsible for normalising the address
// before it reaches persistence, so that lookup and insertion agree.
func (r *UserRepository) GetByEmail(ctx context.Context, email string) (*domain.User, error) {
	query := `SELECT ` + userColumns + ` FROM users WHERE email = $1`
	return r.queryOne(ctx, query, email)
}

// Update persists the mutable fields of a user and refreshes updated_at.
func (r *UserRepository) Update(ctx context.Context, user *domain.User) error {
	const query = `
		UPDATE users
		SET email = $1, password_hash = $2, full_name = $3, role = $4, status = $5, updated_at = NOW()
		WHERE id = $6
		RETURNING updated_at`

	err := r.db.QueryRowContext(ctx, query,
		user.Email,
		user.PasswordHash,
		user.FullName,
		user.Role,
		user.Status,
		user.ID,
	).Scan(&user.UpdatedAt)

	if errors.Is(err, sql.ErrNoRows) {
		return fmt.Errorf("update user %s: %w", user.ID, domain.ErrNotFound)
	}
	if err != nil {
		var pqErr *pq.Error
		if errors.As(err, &pqErr) && pqErr.Code == pgErrUniqueViolation {
			return fmt.Errorf("update user %s: %w", user.ID, domain.ErrConflict)
		}
		return fmt.Errorf("update user %s: %w", user.ID, err)
	}

	return nil
}

// CountActiveAdmins backs the rule that the last active administrator can be
// neither suspended nor demoted (issue #12, section 5.1 point 2).
func (r *UserRepository) CountActiveAdmins(ctx context.Context) (int, error) {
	const query = `SELECT COUNT(*) FROM users WHERE role = $1 AND status = $2`

	var count int
	err := r.db.QueryRowContext(ctx, query, domain.RoleAdmin, domain.UserStatusActive).Scan(&count)
	if err != nil {
		return 0, fmt.Errorf("count active admins: %w", err)
	}

	return count, nil
}

// queryOne centralises row scanning and the ErrNoRows to ErrNotFound
// translation shared by the lookup methods.
func (r *UserRepository) queryOne(ctx context.Context, query string, args ...any) (*domain.User, error) {
	user, err := scanUser(r.db.QueryRowContext(ctx, query, args...))

	if errors.Is(err, sql.ErrNoRows) {
		return nil, domain.ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("query user: %w", err)
	}

	return user, nil
}

// scanUser reads one row shaped like userColumns.
//
// It is shared with the administrative repository, which scans users from
// inside a transaction, so the column order lives in exactly one place: adding
// a column to userColumns without updating this function fails everywhere at
// once rather than in whichever query was forgotten.
func scanUser(scanner rowScanner) (*domain.User, error) {
	var user domain.User

	err := scanner.Scan(
		&user.ID,
		&user.Email,
		&user.PasswordHash,
		&user.FullName,
		&user.Role,
		&user.Status,
		&user.CreatedAt,
		&user.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}

	return &user, nil
}
